spring:
  cloud:
    nacos:
      discovery:
        namespace: fb706e3d-4f7a-4f2e-9890-08692c8c08bd
        username: nacos
        password: nacos
        server-addr: 192.168.52.129:8848
        group: test